name: Deploy to Docker Hub
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker images
        run: docker build -t local -f Dockerfile .

      - name: Run tests
        id: tests
        run: docker run -t -e _TEST_PYTHON_TEST_MODE=true local | grep = | tr -d '\r' | tee "$GITHUB_OUTPUT" | xxd

      - name: Set python version tag
        run: |
          tag=v${{ steps.tests.outputs.major }}.${{ steps.tests.outputs.minor }}.${{ steps.tests.outputs.micro }}
          echo "${tag}" | xxd
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag "${tag}" -f
          git tag "latest" -f
          git push origin "${tag}" -f
          git push origin "latest" -f

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: git
          images: sroaj/truenas-auto-reboot-instances
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.tests.outputs.major }}.${{ steps.tests.outputs.minor }}.${{ steps.tests.outputs.micro }},enable={{is_default_branch}}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/sroaj/truenas-auto-reboot-instances
          subject-digest: ${{ steps.push.outputs.digest }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sroaj/truenas-auto-reboot-instances
          short-description: ${{ github.event.repository.description }}
